apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backup

resources:
  - namespace.yaml
  - infisical-secret.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/managed-by: argocd

