apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi-config
  namespace: strapi
data:
  .env: |
    NODE_ENV=production
    DATABASE_CLIENT=postgres
    DATABASE_HOST=ameciclo-postgres.postgres.database.azure.com
    DATABASE_PORT=5432
    DATABASE_NAME=strapi
    DATABASE_USERNAME=psqladmin
    DATABASE_PASSWORD=YourSecurePassword123!
    ADMIN_JWT_SECRET=***REMOVED***
    JWT_SECRET=***REMOVED***
    APP_KEYS=***REMOVED***
    API_TOKEN_SALT=***REMOVED***
    TRANSFER_TOKEN_SALT=***REMOVED***
    DO_SPACE_KEY=***REMOVED***
    DO_SPACE_SECRET=***REMOVED***
    DO_SPACE_REGION=nyc3
    DO_SPACE_ENDPOINT=https://nyc3.digitaloceanspaces.com
    DO_SPACE_BUCKET=ameciclo-space

