apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: strapi-infisical-secret
  namespace: strapi
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: strapi
      secretsScope:
        projectId: "adb15f17-720e-4a71-b5ae-180492251401"
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: strapi-infisical-managed
    secretNamespace: strapi
  instantUpdates: true

