apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: strapi

resources:
  - namespace.yaml
  - db-init-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: strapi
  app.kubernetes.io/part-of: strapi

