{{- if and .Values.kong.pg.host .Values.kong.pg.password .Values.kong.adminGui.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong.fullname" . }}-db
  labels:
    {{- include "kong.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.kong.pg.host | b64enc }}
  password: {{ .Values.kong.pg.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong.fullname" . }}-session
  labels:
    {{- include "kong.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.kong.adminGui.sessionSecret | b64enc }}
{{- else }}
# WARNING: Kong database and session secrets are not configured.
# Please set the following values:
# - kong.pg.host
# - kong.pg.password
# - kong.adminGui.sessionSecret
{{- end }}

