apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong.fullname" . }}
  labels:
    {{- include "kong.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.proxy.port }}
      targetPort: {{ .Values.service.ports.proxy.targetPort }}
      protocol: {{ .Values.service.ports.proxy.protocol }}
      name: proxy
    - port: {{ .Values.service.ports.proxySSL.port }}
      targetPort: {{ .Values.service.ports.proxySSL.targetPort }}
      protocol: {{ .Values.service.ports.proxySSL.protocol }}
      name: proxy-ssl
    - port: {{ .Values.service.ports.admin.port }}
      targetPort: {{ .Values.service.ports.admin.targetPort }}
      protocol: {{ .Values.service.ports.admin.protocol }}
      name: admin
    - port: {{ .Values.service.ports.adminSSL.port }}
      targetPort: {{ .Values.service.ports.adminSSL.targetPort }}
      protocol: {{ .Values.service.ports.adminSSL.protocol }}
      name: admin-ssl
    - port: {{ .Values.service.ports.manager.port }}
      targetPort: {{ .Values.service.ports.manager.targetPort }}
      protocol: {{ .Values.service.ports.manager.protocol }}
      name: manager
  selector:
    {{- include "kong.selectorLabels" . | nindent 4 }}
