apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: atlas-infisical-secret
  namespace: atlas
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: strapi
      secretsScope:
        projectId: "9ef20fbc-1740-4505-bfd1-90d3e3d678ec"
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: atlas-infisical-managed
    secretNamespace: atlas
  instantUpdates: true

