apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas

resources:
  - traffic-deaths
  - docs

commonLabels:
  app.kubernetes.io/part-of: atlas
  app.kubernetes.io/managed-by: argocd

