apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traffic-deaths-acme
  namespace: atlas
spec:
  redirectRegex:
    regex: ^http://(.*)/.well-known/acme-challenge/(.*)$
    replacement: http://$1/.well-known/acme-challenge/$2
    permanent: false

