apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-groundwork
  namespace: argocd
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-machine-identity
            key: clientId
          clientSecret:
            name: infisical-machine-identity
            key: clientSecret
      secretsScope:
        projectSlug: groundwork-z2e9
        environmentSlug: prod
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-telegram
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-groundwork
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        telegram-token: "{{ .TELEGRAM_BOT_TOKEN }}"
        telegram-chatid: "{{ .TELEGRAM_CHAT_ID }}"
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: TELEGRAM_BOT_TOKEN
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: TELEGRAM_CHAT_ID

