apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: groundwork-infisical-secret
  namespace: argocd
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: argocd
      secretsScope:
        projectId: "2c6394a4-3352-49f1-86fb-634249e3c7cb"
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: groundwork-infisical-managed
    secretNamespace: argocd
  instantUpdates: true

