apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-manager
  namespace: kong
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kong-manager
      port:
        name: manager
  tls:
    - hosts:
        - kong-manager
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-admin
  namespace: kong
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: kong-admin
      port:
        name: admin
  tls:
    - hosts:
        - kong-admin
