apiVersion: v1
kind: Service
metadata:
  name: kong-kong-admin
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: kong
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
