apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-notifications-cm.yaml
  - argocd-infisical-secretstore.yaml

commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: argocd

