apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: strapi

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
# Note: Secrets are managed by Infisical (see kubernetes/infrastructure/infisical/)

commonLabels:
  app.kubernetes.io/name: strapi
  app.kubernetes.io/part-of: strapi

