---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: Don't set namespace here as argocd-ingress needs to be in argocd namespace

resources:
  - namespace.yaml
  - argocd-ingress.yaml
  - subnet-router.yaml

commonLabels:
  app.kubernetes.io/part-of: tailscale
  app.kubernetes.io/managed-by: argocd

