apiVersion: v1
kind: Service
metadata:
  name: atlas-docs
  namespace: atlas
  labels:
    app.kubernetes.io/name: atlas-docs
    app.kubernetes.io/part-of: atlas
    app.kubernetes.io/component: documentation
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: atlas-docs

