apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ameciclo-connector
  namespace: tailscale
spec:
  subnetRouter:
    advertiseRoutes:
      - 10.20.0.0/16  # K3s cluster network
      - 10.43.0.0/16  # K3s service network
  tags:
    - tag:k8s

