---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kube-prometheus-stack.yaml
  - traefik-servicemonitor.yaml
  - traefik-metrics-service.yaml
  - grafana-ingress.yaml
  - traefik-dashboard-configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: argocd

