apiVersion: v2
name: argocd
description: ArgoCD GitOps Continuous Deployment for Kubernetes
type: application
version: 0.1.0
appVersion: "2.10.0"
keywords:
  - argocd
  - gitops
  - continuous-deployment
  - cd
maintainers:
  - name: Ameciclo
    email: dev@ameciclo.org
