apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas

resources:
  - migration-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: atlas
  app.kubernetes.io/managed-by: argocd

