apiVersion: v2
name: kong
description: Kong API Gateway for Kubernetes
type: application
version: 0.1.0
appVersion: "3.4.0"
keywords:
  - kong
  - api-gateway
  - ingress
maintainers:
  - name: Ameciclo
    email: dev@ameciclo.org
