apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-docs
  namespace: atlas
  labels:
    app.kubernetes.io/name: atlas-docs
    app.kubernetes.io/part-of: atlas
    app.kubernetes.io/component: documentation
spec:
  ingressClassName: traefik
  rules:
    - host: docs.atlas.az.ameciclo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-docs
                port:
                  number: 80

