apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zitadel

resources:
  - namespace.yaml
  - zitadel-infisical-secretstore.yaml
  - zitadel-helm-release.yaml
  - zitadel-ingress.yaml

commonLabels:
  app.kubernetes.io/name: zitadel
  app.kubernetes.io/part-of: zitadel
  app.kubernetes.io/managed-by: argocd

