apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-config
  namespace: zitadel
type: Opaque
stringData:
  config.yaml: |
    Database:
      Postgres:
        Host: ameciclo-postgres.postgres.database.azure.com
        User:
          Password: YourSecurePassword123!
        Admin:
          Password: YourSecurePassword123!
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
type: Opaque
stringData:
  # 32 character string (exactly 32 bytes)
  masterkey: "aBcDeFgHiJkLmNoPqRsTuVwXyZ012345"

