apiVersion: v1
kind: Secret
metadata:
  name: zitadel-db-password
  namespace: zitadel
type: Opaque
stringData:
  DATABASE_PASSWORD: "YourSecurePassword123!"
  ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "YourSecurePassword123!"
  ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "YourSecurePassword123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
  namespace: zitadel
type: Opaque
stringData:
  # 32 random bytes base64 encoded (this will be stored as-is)
  masterkey: "/nIVVEh38xxbeOQeK1hqp6IGXOBeGW5CEqUtGBv/SiQ="

